### ISSUE TITLE
筆者紹介

### ISSUE THREAD

**Issue by wamisnet** [Nefry-Community/TutorialBook#16]
記載したい自己紹介をコメントで書いて下さい！

**Comment by wamisnet** [comment]
Nefryのハードウエア＆ソフトウエアの開発者です。個人の活動で始めたNefryという存在がここまで大きくなって感謝の気持ちでいっぱいです！皆さんこれからもよろしくお願いします。

**Comment by pokiiio** [comment]
Androidエンジニアだけどマイコンボードが大好き。Nefry BTを使った電車遅延チェックガジェットを作るハンズオンイベントを開催。京急は神。

**Comment by tokutoku393** [comment]
Webの人。電気風呂での失敗が転じて初心者に優しい電子工作を広める道へ。はんだづけが好き。

**Comment by 1ft-seabass** [comment]
普段はフリーランスのWebフロントエンジニア。インターフェースを作りやすいNefry BTを使ってIoTやMixed Realityへの接続を日々試みている。ウォンバットが好き。
