### ISSUE TITLE
Nefryコンソールの開き方

### ISSUE THREAD

**Issue by tokutoku393** [Nefry-Community/TutorialBook#25]
Nefryのセットアップのところにコンソールの開き方（Nefr Wi-Fiにつなぐor IPにつなぐ）を説明してほしいです

**Comment by wamisnet** [comment]
@tokutoku393 チュートリアル本で扱う範囲を超えるので扱わなくてもいいかなって思ってます

**Comment by wamisnet** [comment]
一応レビューコメントでもあるので大丈夫かな
